model:
  d_model: 128
  nhead: 8
  num_layers: 5
  seq_length: 256
  dropout: 0.1
  ffn_mul: 2
  device: cuda

data:
  data_dir: "./.logs/gptv1vgptv1_traindata/"
  train_split: 0.95
  val_split: 0.05
  type: pov

training:
  batch_size: 256
  epochs: 500
  learning_rate: 0.0001
  weight_decay: 0.01
  save_every: 5
  num_workers: 4
  prefetch_factor: 1
  checkpoint_path: "gpt/checkpoints/model_epoch_30.pt"

generation:
  temperature: 1.0
  max_tokens: 30
  checkpoint_path: "gpt/checkpoints/model_epoch_80.pt"
  prompt: "|gamestart\n|p1|hidden|draw|1"
