model:
  d_model: 128
  nhead: 4
  num_layers: 3
  seq_length: 256
  dropout: 0.1
  device: cuda

data:
  data_dir: "./.logs/test"
  train_split: 0.95
  val_split: 0.05
  type: mixed

training:
  batch_size: 128
  epochs: 200
  learning_rate: 0.001
  weight_decay: 0.01
  save_every: 5
  num_workers: 8
  prefetch_factor: 2

generation:
  temperature: 1.0
  max_tokens: 30
  checkpoint_path: "gpt/checkpoints/model_latest.pt"
  prompt: "|gamestart\n|p1|hidden|draw|1"
