model:
  d_model: 512
  nhead: 32
  num_layers: 15
  seq_length: 256
  dropout: 0.1
  ffn_mul: 2
  device: cuda

data:
  data_dir: "../../../love-letter-logs/logs/"
  train_split: 0.95
  val_split: 0.05
  type: pov
  max_logs: 165000

training:
  batch_size: 128
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.01
  save_every: 5
  num_workers: 8
  prefetch_factor: 2

generation:
  temperature: 1.0
  max_tokens: 30
  checkpoint_path: "gpt/checkpoints/model_epoch_80.pt"
  prompt: "|gamestart\n|p1|hidden|draw|1"
