# Tournament Configuration
bots:
  - name: "GPTBot1"
    command: "python3.11 -m bots.gpt_bot --checkpoint gpt/checkpoints/generation/gen1.pt"
  - name: "GPTBot2"
    command: "python3.11 -m bots.gpt_bot --checkpoint gpt/checkpoints/generation/gen1.pt"

options:
  gamesPerMatch: 200
  logDirectory: "./.logs/gen1_logs"
  reportDirectory: "./.reports"
  timeLimitSeconds: 30
  chunkSize: 1
  firstTo: 1
  tourneyName: "GPTvsGPTSelfPlay-Generation1"
  debug:
    tourney: false  # Debug output for tournament operations
    engine: false   # Debug output for game engine