# Tournament Configuration
bots:
  - name: "GPTBotGen2"
    command: "python3.11 -m bots.gpt_bot --checkpoint gpt/checkpoints/generation/gen2.pt"
  - name: "GPTBotGen3"
    command: "python3.11 -m bots.gpt_bot --checkpoint gpt/checkpoints/generation/gen3.pt"

options:
  gamesPerMatch: 1000000
  logDirectory: "./.logs/gen3-regtest-v2"
  reportDirectory: "./.reports"
  timeLimitSeconds: 60
  chunkSize: 8
  firstTo: 1
  tourneyName: "Gen3vGen2"
  debug:
    tourney: false  # Debug output for tournament operations
    engine: false   # Debug output for game engine