# Tournament Configuration
bots:
  - name: "GPTBot1"
    command: "python3.11 -m bots.gpt_bot"
  - name: "GPTBot2"
    command: "python3.11 -m bots.gpt_bot"

options:
  gamesPerMatch: 25000
  logDirectory: "./.logs/gptv1vgptv1_traindata/"
  reportDirectory: "./.reports"
  timeLimitSeconds: 60
  chunkSize: 8
  firstTo: 1
  tourneyName: "Gen1TrainData"
  debug:
    tourney: false  # Debug output for tournament operations
    engine: false   # Debug output for game engine


#To Run Tournament run
#yarn start:tourney --config ./config/tourney.yaml